# VEYRA — one entry point for everything. Never put machine-specific values in here:
# they belong in profiles/<name>.env (P5).
#
#   make up PROFILE=laptop                 base stack + Wazuh (local)
#   make up PROFILE=laptop WAZUH=remote    base stack only; the router ships via syslog_tcp
#   make up SERVICES="a2 a3 a6"            also start those phases' python services
#   make topics && make test && make lint && make plan-check
#
# Targets that print TODO are owned by a later phase; the phase id is in the message.

SHELL := /bin/bash
.DEFAULT_GOAL := help
.PHONY: help up down ps logs restart build topics wipe-data test test-int lint fmt typecheck ci \
        plan-check wazuh-certs wazuh-logtest console-dev console-build contracts-repo-init \
        e2e-smoke llm-warm \
        bench-llm bench-throughput demo-reset demo-preflight demo-stage doctor env-print

PROFILE      ?= laptop
WAZUH        ?= local
SERVICES     ?=
PROFILE_FILE := profiles/$(PROFILE).env
RUNTIME_ENV  := .env.runtime
COMPOSE_BASE := -f compose/docker-compose.yml
UV           := uv

ifeq ($(WAZUH),local)
COMPOSE_FILES := $(COMPOSE_BASE) -f compose/docker-compose.wazuh.yml
else
COMPOSE_FILES := $(COMPOSE_BASE)
endif

COMPOSE_PROFILE_ARGS := $(foreach s,$(SERVICES),--profile $(s))
DC := docker compose --env-file $(RUNTIME_ENV) $(COMPOSE_FILES) $(COMPOSE_PROFILE_ARGS)

# ---------------------------------------------------------------------------- help
help: ## show this help
	@echo "VEYRA make targets (PROFILE=$(PROFILE), WAZUH=$(WAZUH))"
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

# Merge profile -> .env.local -> current shell into one file compose can read.
# Load order matches 03_INFRA_PROFILES.md §1.
$(RUNTIME_ENV): $(PROFILE_FILE) $(wildcard .env.local)
	@test -f $(PROFILE_FILE) || { echo "no such profile: $(PROFILE_FILE)"; exit 1; }
	@{ echo "# generated by make from $(PROFILE_FILE) — do not edit"; \
	   grep -vE '^\s*(#|$$)' $(PROFILE_FILE); \
	   test -f .env.local && grep -vE '^\s*(#|$$)' .env.local || true; } > $@
	@echo "wrote $@ (profile $(PROFILE))"

env-print: $(RUNTIME_ENV) ## show the merged runtime env
	@cat $(RUNTIME_ENV)

# ---------------------------------------------------------------------------- stack
up: $(RUNTIME_ENV) ## build if needed and start the stack
	mkdir -p data/{kafka,clickhouse,immudb,caddy,vault,keys,state,sinks/wazuh,sinks/partner,vector/dmz,vector/core,llm_cache,wazuh}
	$(DC) up -d --remove-orphans
	@echo "console: http://localhost:8080   wazuh: https://localhost:8443"

build: $(RUNTIME_ENV) ## build the python service image
	$(DC) build

down: $(RUNTIME_ENV) ## stop the stack (data is kept)
	$(DC) down --remove-orphans

ps: $(RUNTIME_ENV) ## container status
	$(DC) ps

logs: $(RUNTIME_ENV) ## tail logs: make logs S=kafka
	$(DC) logs -f --tail=200 $(S)

restart: $(RUNTIME_ENV) ## restart one service: make restart S=normalizer
	$(DC) restart $(S)

wipe-data: ## delete every runtime volume (asks first)
	@read -p "delete ./data entirely? [y/N] " a; [ "$$a" = y ] || exit 1
	$(DC) down -v --remove-orphans 2>/dev/null || true
	sudo rm -rf data
	@echo "data/ removed"

contracts-repo-init: ## give the contract registry its own git history (idempotent)
	@if [ -d contracts-repo/.git ]; then echo "contracts-repo already initialised"; else \
	  git -C contracts-repo init -q . && \
	  git -C contracts-repo add -A && \
	  git -C contracts-repo -c user.email=veyra@localhost -c user.name="VEYRA seed" \
	    commit -q -m "seed: library contracts from the tracked seed files" && \
	  git -C contracts-repo tag seed && echo "contracts-repo initialised at tag seed"; fi

topics: $(RUNTIME_ENV) ## create every IF-TOPICS topic with profile partitions
	$(UV) run --env-file $(RUNTIME_ENV) python -m veyra_common.topics

# ---------------------------------------------------------------------------- quality
test: ## unit tests (no containers needed)
	$(UV) run pytest -q -m "not int"

test-int: $(RUNTIME_ENV) ## integration tests against the running stack
	$(UV) run --env-file $(RUNTIME_ENV) pytest -q -m int

lint: ## ruff check + format check
	$(UV) run ruff check .
	$(UV) run ruff format --check .

fmt: ## apply ruff fixes and formatting
	$(UV) run ruff check --fix .
	$(UV) run ruff format .

typecheck: ## mypy (lenient)
	$(UV) run mypy packages services tools

plan-check: ## list plan files whose contracts header is stale
	$(UV) run python tools/plan_check.py

ci: lint test plan-check ## what CI runs
	@echo "ci: green"

doctor: ## check the host has what the laptop profile needs
	$(UV) run python tools/doctor.py

# ---------------------------------------------------------------------------- wazuh
wazuh-certs: ## generate Wazuh certificates into data/wazuh/certs (run once)
	mkdir -p data/wazuh/certs
	docker run --rm \
		-v $(PWD)/compose/wazuh/certs.yml:/config/certs.yml:ro \
		-v $(PWD)/data/wazuh/certs:/certificates \
		--entrypoint /bin/bash wazuh/wazuh-certs-generator:0.0.2 \
		-c "/entrypoint.sh"
	@# The generator writes root-ca-manager.pem itself and sets container UIDs; do not chown.
	@echo "certs written to data/wazuh/certs"

wazuh-logtest: ## pipe a sample NDJSON line through the manager's rule engine
	@test -n "$(LINE)" || { echo 'usage: make wazuh-logtest LINE=<json line>'; exit 1; }
	echo '$(LINE)' | docker exec -i veyra-wazuh-manager /var/ossec/bin/wazuh-logtest -v

# ---------------------------------------------------------------------------- console
console-dev: ## run the console dev server (C5)
	@echo "TODO (C5): console/ is scaffolded in C5 — Vite dev server behind caddy"

console-build: ## build the static console bundle (C5)
	@echo "TODO (C5): npm ci && npm run build -> console/dist, served by caddy"

# ---------------------------------------------------------------------------- stubs owned by later phases
e2e-smoke: ## end-to-end smoke test (CP1, tools/checkpoints/cp1.py)
	@echo "TODO (CP1): tools/checkpoints/cp1.py — syslog line -> Wazuh, segment sealed, CH rows"

llm-warm: ## preload the LLM into VRAM (C4)
	@echo "TODO (C4): ollama run \$$VEYRA_LLM_MODEL with a warmup prompt, keep_alive 30m"

bench-llm: ## draft accuracy + latency bench (C4)
	@echo "TODO (C4): tools/bench/llm_bench.py -> reports/C4-bench-<machine>.md"

bench-throughput: ## normalizer/router scaling bench (A6)
	@echo "TODO (A6): tools/bench/throughput.py -> reports/A6-bench-<machine>.md"

demo-reset: ## reset to the pre-demo state (B7)
	@echo "TODO (B7): POST /api/demo/reset — wipe + reseed in under 90s"

demo-preflight: ## pre-demo checks (B7 + S2)
	@echo "TODO (B7): GET /api/demo/preflight — health, RAM, LLM, rules, clock, disk"

demo-stage: ## run one demo stage: make demo-stage N=3 (B7)
	@echo "TODO (B7): POST /api/demo/stage/$(N)"
