"""Pydantic v2 models for every record in docs/plan/02_CONTRACTS.md.

Import from here, never from the submodules, so record types can move without
breaking consumers::

    from veyra_common.models import Envelope, Ulpf, LineageRecord
"""

from veyra_common.models.control import (
    KEY_PREFIX_APIKEY,
    KEY_PREFIX_CONTRACT,
    KEY_PREFIX_ENRICH,
    KEY_PREFIX_SOURCE,
    KEY_PREFIX_VOCAB,
    KEY_ROUTES,
    ApiKeyMessage,
    CandidateContract,
    ContractMessage,
    ContractState,
    EnrichMessage,
    RoutesMessage,
    RouteSpec,
    SourceMessage,
    VocabMessage,
    control_key,
)
from veyra_common.models.envelope import (
    UNREGISTERED_SOURCE,
    UNREGISTERED_TENANT,
    UNREGISTERED_VENDOR,
    Auth,
    AuthMethod,
    Custody,
    Envelope,
    Framing,
    FramingMethod,
    ReplayBlock,
    ReplayEnvelope,
    Transport,
    Zone,
)
from veyra_common.models.norm import (
    Category,
    ClassHint,
    Confidence,
    Conformance,
    ContractRef,
    EncodingInfo,
    NormEvent,
    RawRef,
    TemplateRef,
    TimeInfo,
    Ulpf,
)
from veyra_common.models.records import (
    AuditRecord,
    DlqRecord,
    LineageRecord,
    ReasonCode,
    Receipt,
    ReceiptStatus,
    ShadowRecord,
    SignedRoot,
    VaultIndexEvent,
    VaultIndexRecord,
    VaultIndexSegment,
)

__all__ = [
    "KEY_PREFIX_APIKEY",
    "KEY_PREFIX_CONTRACT",
    "KEY_PREFIX_ENRICH",
    "KEY_PREFIX_SOURCE",
    "KEY_PREFIX_VOCAB",
    "KEY_ROUTES",
    "UNREGISTERED_SOURCE",
    "UNREGISTERED_TENANT",
    "UNREGISTERED_VENDOR",
    "ApiKeyMessage",
    "AuditRecord",
    "Auth",
    "AuthMethod",
    "CandidateContract",
    "Category",
    "ClassHint",
    "Confidence",
    "Conformance",
    "ContractMessage",
    "ContractRef",
    "ContractState",
    "Custody",
    "DlqRecord",
    "EncodingInfo",
    "EnrichMessage",
    "Envelope",
    "Framing",
    "FramingMethod",
    "LineageRecord",
    "NormEvent",
    "RawRef",
    "ReasonCode",
    "Receipt",
    "ReceiptStatus",
    "ReplayBlock",
    "ReplayEnvelope",
    "RouteSpec",
    "RoutesMessage",
    "ShadowRecord",
    "SignedRoot",
    "SourceMessage",
    "TemplateRef",
    "TimeInfo",
    "Transport",
    "Ulpf",
    "VaultIndexEvent",
    "VaultIndexRecord",
    "VaultIndexSegment",
    "VocabMessage",
    "Zone",
    "control_key",
]
